apiVersion: devops.crayflow.xyz/v1
kind: Workflow
metadata:
  name: sample
spec:
  # TODO(user): Add fields here
  creator: "buhuipao"
  vars:
    - key: key1
      value: value1
    - key: json1
      value: |
        {
          "key": "value"
        }
  resets:
    - "step1"
  serviceAccountName: crayflow-default
  nodes:
    - name: "step1"
      timeout: 600
      dependencies:
      container:
        name: "hello"
        image: "busybox:latest"
        command: ["sh"]
        args: 
          - -c
          - |
            echo "hello, busybox."
            sleep 300
        resources: # limit the resources
          limits:
            memory: 1024Mi
            cpu: 300m
    #- name: "step2"
    #  timeout: 600
    #  dependencies:
    #    - "step1"
    #  container:
    #    name: "hello"
    #    image: "docker/whalesay"
    #    command: [ cowsay ]
    #    args: [ "hello world" ]
    #    resources: # limit the resources
    #      limits:
    #        memory: 32Mi
    #        cpu: 100m