apiVersion: devops.crayflow.xyz/v1
kind: Workflow
metadata:
  name: workflow-sample
spec:
  # TODO(user): Add fields here
  creator: "buhuipao"
  resets:
    - "step1"
  clear: true
  nodes:
    - name: "step1"
      timeout: 600
      container:
        name: "hello"
        image: "docker/whalesay"
        command: [ cowsay ]
        args: [ "hello world" ]
        resources: # limit the resources
          limits:
            memory: 32Mi
            cpu: 100m
    - name: "step2"
      timeout: 600
      dependencies:
        - "step1"
      container:
        name: "hello"
        image: "docker/whalesay"
        command: [ cowsay ]
        args: [ "hello world" ]
        resources: # limit the resources
          limits:
            memory: 32Mi
            cpu: 100m
